# Generated by Django 5.0 on 2023-12-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(choices=[('HERSHEY_COMPLEX', 'HERSHEY_COMPLEX'), ('HERSHEY_SIMPLEX', 'HERSHEY_SIMPLEX')], max_length=50)),
                ('scale', models.PositiveSmallIntegerField()),
                ('thickness', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_width', models.PositiveIntegerField(max_length=4000)),
                ('video_height', models.PositiveIntegerField(max_length=4000)),
                ('fps', models.PositiveIntegerField(max_length=120)),
                ('seconds', models.PositiveIntegerField(max_length=300)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.font')),
            ],
        ),
    ]
