# Generated by Django 5.0 on 2023-12-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='text',
            field=models.CharField(default='aaa', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='font',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('White', 'White'), ('Black', 'Black')], default='White', max_length=20),
        ),
        migrations.AlterField(
            model_name='font',
            name='font',
            field=models.CharField(choices=[('COMPLEX', 3), ('SIMPLEX', 0)], default='COMPLEX', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='fps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='seconds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='video_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='video_width',
            field=models.PositiveIntegerField(),
        ),
    ]
