# Generated by Django 5.0 on 2023-12-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_alter_font_font_alter_font_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='name',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='font',
            name='font',
            field=models.CharField(choices=[('3', 'COMPLEX'), ('0', 'SIMPLEX')], default=3, max_length=50),
        ),
    ]
