# Generated by Django 5.0 on 2023-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0005_alter_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='font',
            name='color',
            field=models.CharField(choices=[('0 0 255', 'Red'), ('0 255 0', 'Green'), ('255 0 0', 'Blue'), ('255 255 255', 'White'), ('0 0 0', 'Black')], default='White', max_length=20),
        ),
    ]
