# Generated by Django 5.0 on 2023-12-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0006_ticker_video_alter_font_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='fps',
        ),
    ]
